/**
 * Python script templates (query and streaming variants) for the generated
 * SDK script. Split out of generatePythonSdk/index.ts (file-size guard).
 */

import type { ExtractedParams } from './params';
import { buildApiKeyComment, buildExportNotes } from './optionBuilders';

/** Render docstring notes for settings the Python SDK cannot express. */
function buildNotesBlock(p: ExtractedParams): string {
	const notes = buildExportNotes(p);
	if (notes.length === 0) return '';
	return `\nNotes:\n${notes.map((note) => `    - ${note}`).join('\n')}\n`;
}

export function assembleQueryScript(
	mainImports: string[],
	typesImports: string[],
	optionsBody: string,
	prompt: string,
	hasPrompt: boolean,
	p: ExtractedParams,
): string {
	const promptDefault = hasPrompt ? `"${prompt}"` : '"Describe your task here"';
	const hasStructured = p.structuredOutput;

	const apiKeyComment = buildApiKeyComment(p);
	const notesBlock = buildNotesBlock(p);
	const typesImportLine = typesImports.length > 0
		? `\nfrom claude_agent_sdk.types import (\n${typesImports.map((i) => `    ${i},`).join('\n')}\n)\n`
		: '';

	return `#!/usr/bin/env python3
"""
Claude Agent SDK Script
Generated by n8n Claude Agent SDK node.

Usage:
    python claude_agent.py
    python claude_agent.py --prompt "Your task here"

Requirements:
    pip install claude-agent-sdk
${apiKeyComment}${notesBlock}"""
from __future__ import annotations

import argparse
import json
import sys

import anyio

from claude_agent_sdk import (
${mainImports.map((i) => `    ${i},`).join('\n')}
)
${typesImportLine}


def build_options() -> ClaudeAgentOptions:
    """Build agent configuration."""
    return ClaudeAgentOptions(
${optionsBody.replace(/^ {4}options = ClaudeAgentOptions\(\n?/, '').replace(/\n {4}\)$/, '')}
    )


def handle_message(message: AssistantMessage | SystemMessage | ResultMessage) -> None:
    """Process a single SDK message."""

    if isinstance(message, AssistantMessage):
        for block in message.content:
            if isinstance(block, TextBlock):
                print(block.text, end="", flush=True)
            elif isinstance(block, ToolUseBlock):
                print(f"\\n--- Tool: {block.name} ---", file=sys.stderr)
            elif isinstance(block, ToolResultBlock):
                status = "error" if block.is_error else "ok"
                print(f"--- Result ({status}) ---", file=sys.stderr)

    elif isinstance(message, SystemMessage):
        if message.subtype == "init":
            session_id = message.data.get("session_id", "")
            print(f"Session: {session_id}", file=sys.stderr)

    elif isinstance(message, ResultMessage):
        print()  # newline after streamed text
        print(f"--- Done ({message.num_turns} turns, {message.duration_ms}ms) ---", file=sys.stderr)
        if message.total_cost_usd:
            print(f"Cost: \${message.total_cost_usd:.4f}", file=sys.stderr)
        if message.is_error:
            print(f"Error: {message.result}", file=sys.stderr)${hasStructured ? `
        if message.structured_output:
            print(json.dumps(message.structured_output, indent=2))` : ''}


async def main() -> None:
    parser = argparse.ArgumentParser(description="Run Claude agent task")
    parser.add_argument("--prompt", "-p", default=${promptDefault}, help="Task prompt")
    args = parser.parse_args()

    options = build_options()

    async for message in query(prompt=args.prompt, options=options):
        handle_message(message)


if __name__ == "__main__":
    anyio.run(main)
`;
}

export function assembleStreamingScript(
	mainImports: string[],
	typesImports: string[],
	optionsBody: string,
	prompt: string,
	hasPrompt: boolean,
	p: ExtractedParams,
): string {
	const promptDefault = hasPrompt ? `"${prompt}"` : '"Describe your task here"';
	const hasStructured = p.structuredOutput;

	// Streaming needs StreamEvent (types submodule) + UserMessage (main)
	if (!typesImports.includes('StreamEvent')) typesImports.push('StreamEvent');
	typesImports.sort();
	if (!mainImports.includes('UserMessage')) mainImports.push('UserMessage');
	mainImports.sort();

	const apiKeyComment = buildApiKeyComment(p);
	const notesBlock = buildNotesBlock(p);
	const typesImportLine = typesImports.length > 0
		? `\nfrom claude_agent_sdk.types import (\n${typesImports.map((i) => `    ${i},`).join('\n')}\n)\n`
		: '';

	return `#!/usr/bin/env python3
"""
Claude Agent SDK Script (Streaming)
Generated by n8n Claude Agent SDK node.

Usage:
    python claude_agent.py
    python claude_agent.py --prompt "Your task here"
    python claude_agent.py --interactive   # multi-turn conversation

Requirements:
    pip install claude-agent-sdk
${apiKeyComment}${notesBlock}"""
from __future__ import annotations

import argparse
import json
import sys

import asyncio

from claude_agent_sdk import (
${mainImports.map((i) => `    ${i},`).join('\n')}
)
${typesImportLine}


def build_options() -> ClaudeAgentOptions:
    """Build agent configuration."""
    return ClaudeAgentOptions(
${optionsBody.replace(/^ {4}options = ClaudeAgentOptions\(\n?/, '').replace(/\n {4}\)$/, '')}
    )


def handle_message(msg: AssistantMessage | SystemMessage | ResultMessage | UserMessage | StreamEvent) -> None:
    """Process a single SDK message."""

    if isinstance(msg, AssistantMessage):
        for block in msg.content:
            if isinstance(block, TextBlock):
                print(block.text, end="", flush=True)
            elif isinstance(block, ToolUseBlock):
                print(f"\\n--- Tool: {block.name} ---", file=sys.stderr)
            elif isinstance(block, ToolResultBlock):
                status = "error" if block.is_error else "ok"
                print(f"--- Result ({status}) ---", file=sys.stderr)

    elif isinstance(msg, SystemMessage):
        if msg.subtype == "init":
            session_id = msg.data.get("session_id", "")
            print(f"Session: {session_id}", file=sys.stderr)

    elif isinstance(msg, ResultMessage):
        print()
        print(f"--- Done ({msg.num_turns} turns, {msg.duration_ms}ms) ---", file=sys.stderr)
        if msg.total_cost_usd:
            print(f"Cost: \${msg.total_cost_usd:.4f}", file=sys.stderr)
        if msg.is_error:
            print(f"Error: {msg.result}", file=sys.stderr)${hasStructured ? `
        if msg.structured_output:
            print(json.dumps(msg.structured_output, indent=2))` : ''}

    elif isinstance(msg, StreamEvent):
        # Real-time token deltas — extract text from API events
        delta = msg.event.get("delta", {})
        if delta.get("type") == "text_delta":
            print(delta.get("text", ""), end="", flush=True)


async def run_single(prompt: str) -> None:
    """Execute a single task."""
    options = build_options()

    async with ClaudeSDKClient(options=options) as client:
        await client.query(prompt)
        async for msg in client.receive_response():
            handle_message(msg)


async def run_interactive() -> None:
    """Interactive multi-turn conversation."""
    options = build_options()

    async with ClaudeSDKClient(options=options) as client:
        print("Interactive mode (Ctrl+C to exit)\\n", file=sys.stderr)

        while True:
            try:
                prompt = input("You: ")
            except (EOFError, KeyboardInterrupt):
                print("\\nBye.", file=sys.stderr)
                break

            if not prompt.strip():
                continue

            await client.query(prompt)
            async for msg in client.receive_response():
                handle_message(msg)
            print()  # blank line between turns


async def main() -> None:
    parser = argparse.ArgumentParser(description="Run Claude agent task (streaming)")
    parser.add_argument("--prompt", "-p", default=${promptDefault}, help="Task prompt")
    parser.add_argument("--interactive", "-i", action="store_true", help="Multi-turn conversation")
    args = parser.parse_args()

    if args.interactive:
        await run_interactive()
    else:
        await run_single(args.prompt)


if __name__ == "__main__":
    asyncio.run(main())
`;
}
